version: "3.8"

services:
  # Spring Boot Backend
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: springboot-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/projetcomparateur?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 8084
    ports:
      - "8084:8084"

  # Angular Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
